### ISSUE TITLE
SNAPSHOT.jar is not getting created

### ISSUE THREAD

**Issue by Pavan637** [BauerLab/GeMaIn#2]
Hello all,
I have followed steps given here for buildng Variant Spark. But i am not able to see any SNAPSHOT.jar file being created in target folder.
Kindly suggest in this regard.

**Comment by Pavan637** [comment]
I am getting follwoing error, when  i run variantspark.sh file without building.
./variantspark.sh
Warning: Master yarn-client is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
MASTER: local
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 16
        at au.csiro.obr17q.variantspark.PopulationMap$$anonfun$2.apply(PopulationMap.scala:33)
        at au.csiro.obr17q.variantspark.PopulationMap$$anonfun$2.apply(PopulationMap.scala:29)
        at scala.collection.immutable.List.map(List.scala:273)
        at au.csiro.obr17q.variantspark.PopulationMap.<init>(PopulationMap.scala:29)
        at au.csiro.obr17q.variantspark.VcfClustering$.main(VcfClustering.scala:74)
        at au.csiro.obr17q.variantspark.VcfClustering.main(VcfClustering.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Kindly suggest

**Comment by Pavan637** [comment]
Hello 
Instead of "mvn build", try "mvn package"
You will be able to see jar files created in target folder.
